---
title: 'Lesson 9 - Homework'
subtitle: 'Data visualisation with R'
author: "Beate Kamlage"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  bookdown::pdf_document2:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(dplyr)
library(tidyr)
library(ggplot2)
library(gapminder)
library(stargazer)
library(kableExtra)
#if you want to comment out something, do it inside the chunk. hashtag outside of a chunk is interpreted as tabulator/name of chapters of the text, e.g. # 1.Header_Chapter und ## for 1.1 Subheader_Chapter. CAVE! The Space between # and Text is mandatory. You do not need to number manually. In case a data frame etc is defined within a chunk, comment the call of the object out.Otherwise it will appear in the knitted output. The numbering of Tables and figures is done automatically.
```

# World population by continent in 2007


## Table
Table 1 reports population data by continent in 2007 as a percentage of the world’s population.

```{r}
## population by continent in 2007
pop_continent <- gapminder %>% 
  filter(year == 2007) %>% 
  group_by(continent) %>%
  summarise(pop = sum(pop))

#pop_continent

perc_pop_continent<- mutate (pop_continent, perc = pop/sum (pop) * 100) 


#perc_pop_continent

pop_table <- perc_pop_continent %>%
  select(continent, perc) %>% 
  kbl(booktabs = TRUE,
      format.args = list(decimal.mark = '.',
                         digits=2),
      caption = "World population by continent, year 2007. Source: Gapminder",
      col.names = c("Continent",
                    "Population (in %)")) %>% 
  kable_styling(latex_options = c("hold_position"))

pop_table

```
\newpage
## Pie Chart
```{r figure, fig.align = "center", out.width = '80%', out.height = '30%', fig.cap = "World population by continent, year 2007. Source: Gapminder."}


ggplot(pop_continent, aes(x="", y=pop, fill=continent)) +
  geom_bar(stat="identity", width=1,color="white") +
  coord_polar("y", start=0) +
  labs(x = NULL, y = NULL, fill =NULL) +
  theme_classic() +
  theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
  scale_fill_manual(values = continent_colors) +
    theme(legend.position = "bottom")

```
From Figure 1 we can see that Asia is the most populous continent. In 2007, the percentage of the population of the Asian continent represents
```{r,echo=FALSE,eval=TRUE}
round(perc_pop_continent$perc[3], digits=2)
```
60.98% of the world’s population.

